### PR TITLE
some improvements

### PR DESCRIPTION
**Pull request by williamdemeo**
including Robert Lewis's improvements upon my improvements.

### CODE REVIEW

**Comment by avigad** [comment]
@williamdemeo Thanks for this. But I already incorporated the section on equivalence relations and closed #16. Could you rebase on top of the current version? If that is hard for you, don't worry about it, and I'll make the changes by hand. (I am traveling now but I can do this in early January.)

**Comment by williamdemeo** [comment]
Hi Jeremy, That's weird.  I did `git fetch upstream` and `git merge upstream/master` before submitting this pull request.  Apparently my fork was out-of-date and didn't have, e.g., Robert's modifications of the section on equivalence relations.  There were conflicts, but I used meld to resolve and merge all the differences before submitting the pull request.  Perhaps I should have rebased on top of the current version in a more direct way...? I suppose the easiest would be to delete my fork, make a fresh fork, and then incorporate my latest changes by hand.  Let me know if that's better and I'll do it.

**Comment by avigad** [comment]
I don't know why the fetch and merge did not get the latest version. You can type `git remote -v` to make sure that `upstream` refers to the master branch on `leanprover`. Also, it is better to use `rebase` rather than `merge` to keep the commit record clean.

You could use an interactive rebase (`rebase -i`) to drop the commits that are no longer relevant. But in this case, since the changes are small (and anyhow I need to review and test them), it will be probably be easiest for me to make them manually. I'll do that when I am back in Pittsburgh.

**Comment by williamdemeo** [comment]
Okay, thanks.  Sorry for the inconvenience.  Next time I'll use rebase.

**Comment by avigad** [comment]
Note: I am leaving `anti_symmetric`, since that is the name used in the core library. (I also prefer `antisymmetric`. We should be able to fix it in a future version of Lean.)

**Pull request closed without merging**
